version: '3.3'

services:
  web:
    build: .
    image: katerinasys/skyprohosting1:master-3250837485
    ports:
      - "8080:25000"
    environment:
      - DB_PASSWORD=db_password
      - DB_USER=db_user
      - DB_NAME=db_name

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name

